export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_CLEAR_ERRORS = 'AUTH_CLEAR_ERRORS';

export const LOADING_USER = 'LOADING_USER';
export const SET_USER = 'SET_USER';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
