export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_CLEAR_ERRORS = 'AUTH_CLEAR_ERRORS';

// export const LOADING_USER = 'LOADING_USER';
export const SET_USER = 'SET_USER';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_ADDITIONAL_DATA_USER = 'SET_ADDITIONAL_DATA_USER';

export const SET_VISIBILITY_COURSE_MODAL = 'SET_VISIBILITY_COURSE_MODAL';
export const SET_VISIBILITY_DELETE_MODAL = 'SET_VISIBILITY_DELETE_MODAL';
export const SET_TOASTER_MESSAGE = 'SET_TOASTER_MESSAGE';
export const CLEAR_COURSE_ERRORS = 'CLEAR_COURSE_ERRORS';
export const SELECT_COURSE = 'SELECT_COURSE';
export const UNSELECT_COURSE = 'UNSELECT_COURSE';

export const IS_REQUESTING_COURSES = 'IS_REQUESTING_COURSES';
export const SUCCESS_GET_COURSES = 'SUCCESS_GET_COURSES';
export const FAILED_GET_COURSES = 'FAILED_GET_COURSES';

export const IS_REQUESTING_COURSE = 'IS_REQUESTING_COURSE';
export const SUCCESS_GET_COURSE = 'SUCCESS_GET_COURSE';
export const FAILED_GET_COURSE = 'FAILED_GET_COURSE';

export const REQUEST_ADD_COURSE = 'REQUEST_ADD_COURSE';
export const SUCCESS_ADD_COURSE = 'SUCCESS_ADD_COURSE';
export const FAILED_ADD_COURSE = 'FAILED_ADD_COURSE';

export const REQUEST_EDIT_COURSE = 'REQUEST_EDIT_COURSE';
export const SUCCESS_EDIT_COURSE = 'SUCCESS_EDIT_COURSE';
export const FAILED_EDIT_COURSE = 'FAILED_EDIT_COURSE';

export const REQUEST_DELETE_COURSE = 'REQUEST_DELETE_COURSE';
export const SUCCESS_DELETE_COURSE = 'SUCCESS_DELETE_COURSE';
export const FAILED_DELETE_COURSE = 'FAILED_DELETE_COURSE';

export const REQUEST_ADD_CONTENT = 'REQUEST_ADD_CONTENT';
export const SUCCESS_ADD_CONTENT = 'SUCCESS_ADD_CONTENT';
export const FAILED_ADD_CONTENT = 'FAILED_ADD_CONTENT';

export const REQUEST_EDIT_CONTENT = 'REQUEST_EDIT_CONTENT';
export const SUCCESS_EDIT_CONTENT = 'SUCCESS_EDIT_CONTENT';
export const FAILED_EDIT_CONTENT = 'FAILED_EDIT_CONTENT';

export const REQUEST_DELETE_CONTENT = 'REQUEST_DELETE_CONTENT';
export const SUCCESS_DELETE_CONTENT = 'SUCCESS_DELETE_CONTENT';
export const FAILED_DELETE_CONTENT = 'FAILED_DELETE_CONTENT';

export const REQUEST_NEW_COURSES = 'REQUEST_NEW_COURSES';
export const SUCCESS_GET_NEW_COURSES = 'SUCCESS_GET_NEW_COURSES';
export const FAILED_GET_NEW_COURSES = 'FAILED_GET_NEW_COURSES';

export const REQUEST_COURSE_DETAILS = 'REQUEST_COURSE_DETAILS';
export const SUCCESS_GET_COURSE_DETAILS = 'SUCCESS_GET_COURSE_DETAILS';
export const FAILED_GET_COURSE_DETAILS = 'FAILED_GET_COURSE_DETAILS';

export const REQUEST_COURSE_RATINGS = 'REQUEST_COURSE_RATINGS';
export const SUCCESS_GET_COURSE_RATINGS = 'SUCCESS_GET_COURSE_RATINGS';
export const FAILED_GET_COURSE_RATINGS = 'FAILED_GET_COURSE_RATINGS';

export const REQUEST_ENROLL_COURSE = 'REQUEST_ENROLL_COURSE';
export const SUCCESS_ENROLL_COURSE = 'SUCCESS_ENROLL_COURSE';
export const FAILED_ENROLL_COURSE = 'FAILED_ENROLL_COURSE';

export const REQUEST_GET_ENROLLED_COURSES = 'REQUEST_GET_ENROLLED_COURSES';
export const SUCCESS_GET_ENROLLED_COURSES = 'SUCCESS_GET_ENROLLED_COURSES';
export const FAILED_GET_ENROLLED_COURSES = 'FAILED_GET_ENROLLED_COURSES';

export const REQUEST_ADD_RATING = 'REQUEST_ADD_RATING';
export const SUCCESS_ADD_RATING = 'SUCCESS_ADD_RATING';
export const FAILED_ADD_RATING = 'FAILED_ADD_RATING';

export const SET_VISIBILITY_RATINGS_MODAL = 'SET_VISIBILITY_RATINGS_MODAL';
export const SET_TOASTER_MESSAGE_USER = 'SET_TOASTER_MESSAGE_USER';
export const SET_SELECTED_COURSE = 'SET_SELECTED_COURSE';
