export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_CLEAR_ERRORS = 'AUTH_CLEAR_ERRORS';

export const LOADING_USER = 'LOADING_USER';
export const SET_USER = 'SET_USER';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

export const SET_VISIBILITY_COURSE_MODAL = 'SET_VISIBILITY_COURSE_MODAL';
export const SET_VISIBILITY_DELETE_MODAL = 'SET_VISIBILITY_DELETE_MODAL';
export const SET_TOASTER_MESSAGE = 'SET_TOASTER_MESSAGE';
export const CLEAR_COURSE_ERRORS = 'CLEAR_COURSE_ERRORS';
export const SELECT_COURSE = 'SELECT_COURSE';
export const UNSELECT_COURSE = 'UNSELECT_COURSE';

export const IS_REQUESTING_COURSES = 'IS_REQUESTING_COURSES';
export const SUCCESS_GET_COURSES = 'SUCCESS_GET_COURSES';
export const FAILED_GET_COURSES = 'FAILED_GET_COURSES';

export const IS_REQUESTING_COURSE = 'IS_REQUESTING_COURSE';
export const SUCCESS_GET_COURSE = 'SUCCESS_GET_COURSE';
export const FAILED_GET_COURSE = 'FAILED_GET_COURSE';

export const REQUEST_ADD_COURSE = 'REQUEST_ADD_COURSE';
export const SUCCESS_ADD_COURSE = 'SUCCESS_ADD_COURSE';
export const FAILED_ADD_COURSE = 'FAILED_ADD_COURSE';

export const REQUEST_EDIT_COURSE = 'REQUEST_EDIT_COURSE';
export const SUCCESS_EDIT_COURSE = 'SUCCESS_EDIT_COURSE';
export const FAILED_EDIT_COURSE = 'FAILED_EDIT_COURSE';

export const REQUEST_DELETE_COURSE = 'REQUEST_DELETE_COURSE';
export const SUCCESS_DELETE_COURSE = 'SUCCESS_DELETE_COURSE';
export const FAILED_DELETE_COURSE = 'FAILED_DELETE_COURSE';

export const REQUEST_ADD_CONTENT = 'REQUEST_ADD_CONTENT';
export const SUCCESS_ADD_CONTENT = 'SUCCESS_ADD_CONTENT';
export const FAILED_ADD_CONTENT = 'FAILED_ADD_CONTENT';
